## Matematiksel İşlemler

In [1]:
import numpy as np
v= np.array([1,2,3,4,5])

In [2]:
v-1

array([0, 1, 2, 3, 4])

In [6]:
v*5

array([ 5, 10, 15, 20, 25])

In [5]:
#ufunc

In [7]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [8]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [9]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [10]:
v

array([1, 2, 3, 4, 5])

In [11]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [12]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [13]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [15]:
np.absolute(np.array([-3])) #mutlak değer

array([3])

In [16]:
np.sin(360)

0.9589157234143065

In [17]:
np.cos(180)

-0.5984600690578582

In [18]:
v=np.array([1,2,3])

In [19]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [20]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [21]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the buil

In [22]:
#numpy mathematic cheat sheet yazıp googledan bulunabilir

## İstatistiksel Hesaplamalar

In [24]:
np.mean(v,axis=0)

2.0

In [25]:
v

array([1, 2, 3])

## NumPy ile İki Bilinmeyenli Denklem Çözümü

In [27]:
import numpy as np

5*x0+x1=12
x0+3x1=10

In [29]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [30]:
a

array([[5, 1],
       [1, 3]])

In [31]:
b

array([12, 10])

In [34]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

## Bolum Sonu

In [37]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])

In [38]:
a[:2,:3]

array([[4, 7, 4],
       [2, 5, 0]])

In [39]:
a[3,2] #çalışmaz

IndexError: index 3 is out of bounds for axis 0 with size 3

In [40]:
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])
v[[1,2,3]]

array([3, 6, 9])

In [41]:
np.subtract(v, 2)

array([-2,  1,  4,  7, 10, 13, 16, 19, 22, 25])

In [42]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [43]:
import numpy as np

np.arange(0,10, 2)
 

array([0, 2, 4, 6, 8])

In [45]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
import numpy as np
5*np.array([1,2,3])

array([ 5, 10, 15])

In [47]:
import numpy as np

np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [48]:
np.random.randint(10, size = (3,3,2))

array([[[0, 6],
        [1, 2],
        [5, 8]],

       [[5, 1],
        [6, 1],
        [1, 4]],

       [[0, 7],
        [1, 0],
        [4, 3]]])

In [49]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
import numpy as np

x = np.array([1, 2, 3])

y = np.array([4, 5, 6])

np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])