In [1]:
print("a")

a


Merhaba
_italik_
**kalın**
A üste yeni hücre açar
B alta yeni hücre açar

In [2]:
#Merhaba

In [3]:
#Numerical Python = NumPy

## Neden NumPy

In [5]:
a=[1,2,3,4]
b=[2,3,4,5]
a
b #en sona yazanı çalıştırır

[2, 3, 4, 5]

In [6]:
a

[1, 2, 3, 4]

In [7]:
import numpy as np

In [10]:
a=np.array([1,2,3,4]) #listeye göre daha az maliyetlidir.
b=np.array([2,3,4,5])

In [9]:
a*b

array([ 2,  6, 12, 20])

## NumPy Array'i Oluşturmak

In [11]:
import numpy as np

In [12]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
a=np.array([1,2,3,4,5])

In [14]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14,4,2,13]) #sabit tip bilgisi tutar, hepsi ondalıklı tutuyor

array([ 3.14,  4.  ,  2.  , 13.  ])

In [17]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [18]:
#sifirdan array olusturma

In [22]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [26]:
np.arange(0,31,3) #3 er artan doğrusal dizi

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [27]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(10,4,(3,4))#ortalama 10, standart sapma 3

array([[12.37466949,  8.62059505,  9.5528639 , 16.0258513 ],
       [ 6.07431225,  4.60592524, 10.77980782, -0.44211917],
       [13.30486073,  6.86995165, 15.08736179, 14.12650296]])

In [35]:
np.random.randint(0,10,(3,3)) #0 dan 10 3*3lük random matris

array([[7, 9, 7],
       [8, 6, 8],
       [6, 8, 2]])

## Özellikleri
* ndim : boyut sayısı
* shape: boyut bilgisi
* size : toplam eleman sayısı
* dtype: array veri tipi

In [36]:
import numpy as np

In [37]:
np.random.randint(10,size=10)

array([2, 2, 8, 8, 0, 1, 1, 0, 2, 0])

In [38]:
a=np.random.randint(10,size=10)

In [39]:
a.ndim #boyut sayısı

1

In [41]:
a.shape #boyut bilgisi

(10,)

In [43]:
a.dtype #array veri tipi

dtype('int32')

In [44]:
b=np.random.randint(10,size=(3,5))

In [45]:
b.ndim

2

In [46]:
b.shape

(3, 5)

In [47]:
b.size

15

In [48]:
b.dtype

dtype('int32')

## Yeniden Şekillendirmek

In [49]:
import numpy as np

In [51]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a=np.arange(1,10)

In [54]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a.ndim

1

In [59]:
b=a.reshape((1,9)) #matristir 1 satır 9 sutun 2 boyutludur

In [60]:
b.ndim

2

## Array Birlestirme (Concatenation)

In [61]:
import numpy as np

In [62]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [63]:
np.concatenate([x,y]) #birleştirme

array([1, 2, 3, 4, 5, 6])

In [64]:
z=np.array([7,8,9])

In [68]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# iki boyut

In [116]:
a= np.array([[1,2,3],
           [4,5,6]])

In [117]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [120]:
np.concatenate([a,a],axis=0) # axis ekseni belirtir, 0 sutun ,1 satır

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

## Array Ayırma (Splitting)

In [76]:
import numpy as np

In [77]:
x=np.array([1,2,3,99,99,3,2,1])

In [79]:
np.split(x,[3,5]) #ilk 3 sonra 4,5 i ayır sonra kalanı ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [80]:
a,b,c=np.split(x,[3,5])

In [81]:
a

array([1, 2, 3])

In [82]:
b

array([99, 99])

In [83]:
c

array([3, 2, 1])

In [84]:
#iki boyutlu ayırma

In [85]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.vsplit(m,[2]) #dikey bölme

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [87]:
ust,alt=np.vsplit(m,[2])

In [88]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [94]:
sol,sag=np.hsplit(m,[2])

In [95]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## Array Sıralama(Sorting)

In [97]:
import numpy as np

In [98]:
v=np.array([2,1,4,3,5])

In [99]:
v

array([2, 1, 4, 3, 5])

In [104]:
np.sort(v) #orjnali bozmaz

array([1, 2, 3, 4, 5])

In [105]:
v

array([1, 2, 3, 4, 5])

In [106]:
v.sort() #yapısını bozar

In [107]:
v

array([1, 2, 3, 4, 5])

In [108]:
#iki boyutlu array sıralama

In [111]:
m=np.random.normal(20,5,(3,3))

In [112]:
m

array([[17.1431821 , 19.54148016, 22.11827335],
       [20.78637486, 22.62432074, 13.43886806],
       [22.16595064, 27.51313681, 16.64011704]])

In [113]:
np.sort(m,axis=1)  #1 satır sıralar

array([[17.1431821 , 19.54148016, 22.11827335],
       [13.43886806, 20.78637486, 22.62432074],
       [16.64011704, 22.16595064, 27.51313681]])

In [114]:
np.sort(m,axis=0) #0 sutun sıralar

array([[17.1431821 , 19.54148016, 13.43886806],
       [20.78637486, 22.62432074, 16.64011704],
       [22.16595064, 27.51313681, 22.11827335]])

## Index ile Elemanlara Erişmek

In [121]:
import numpy as np
a= np.random.randint(10,size=10)
a

array([0, 0, 1, 9, 4, 6, 3, 8, 9, 4])

In [122]:
a[0]

0

In [123]:
a[-1]

4

In [124]:
a[0]=100

In [125]:
a

array([100,   0,   1,   9,   4,   6,   3,   8,   9,   4])

In [126]:
m= np.random.randint(10,size=(3,5))
m

array([[1, 5, 5, 0, 7],
       [5, 7, 5, 5, 6],
       [2, 6, 2, 2, 4]])

In [127]:
m[0,0]

1

In [128]:
m[1,1]

7

In [129]:
m[1,4]

6

In [130]:
m[1,4]=99

In [131]:
m

array([[ 1,  5,  5,  0,  7],
       [ 5,  7,  5,  5, 99],
       [ 2,  6,  2,  2,  4]])

In [132]:
m[1,4]=2.2

In [133]:
m

array([[1, 5, 5, 0, 7],
       [5, 7, 5, 5, 2],
       [2, 6, 2, 2, 4]])

## Slicing ile Elemanlara Erişmek (Array Alt Kümesi)

In [134]:
import numpy as np

In [135]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [136]:
a[0:3]

array([20, 21, 22])

In [137]:
a[:3]

array([20, 21, 22])

In [138]:
a[1::2] #1.index ten 2şerli gitme

array([21, 23, 25, 27, 29])

In [139]:
a[0::2]

array([20, 22, 24, 26, 28])

In [140]:
a[0::3]

array([20, 23, 26, 29])

In [141]:
#iki boyutlu slice islemleri

In [142]:
m=np.random.randint(10,size=(5,5))

In [143]:
m

array([[2, 8, 8, 8, 3],
       [1, 3, 6, 0, 0],
       [5, 1, 0, 7, 3],
       [8, 4, 9, 9, 9],
       [4, 5, 6, 7, 1]])

In [146]:
m[:,0] # 0.sutuna eriş

array([2, 1, 5, 8, 4])

In [147]:
m[:,1] #1.sutuna eriş

array([8, 3, 1, 4, 5])

In [149]:
m[0,:] #ilk satır

array([2, 8, 8, 8, 3])

In [151]:
m[0]#ilk satır

array([2, 8, 8, 8, 3])

In [153]:
m[1,:]#ikinci satıra erişme

array([1, 3, 6, 0, 0])

In [155]:
m[0:2,0:3]#0dan 2ye kadar satırları 0dan 3 e kadar sutunları al

array([[2, 8, 8],
       [1, 3, 6]])

In [156]:
m[::,:2]#tüm satırlar ile 2ye kadar sutunları al

array([[2, 8],
       [1, 3],
       [5, 1],
       [8, 4],
       [4, 5]])

In [157]:
m[:,0:2]#tüm satırlar ile 2ye kadar sutunları al

array([[2, 8],
       [1, 3],
       [5, 1],
       [8, 4],
       [4, 5]])

In [160]:
m[1:3,0:2] #1den 3 e kadar satırları ile 0dan 2 ye kadar sutunları al

array([[1, 3],
       [5, 1]])

In [161]:
m

array([[2, 8, 8, 8, 3],
       [1, 3, 6, 0, 0],
       [5, 1, 0, 7, 3],
       [8, 4, 9, 9, 9],
       [4, 5, 6, 7, 1]])

## Alt Küme Üzerinde İşlem Yapmak

In [164]:
import numpy as np
a = np.random.randint(10,size=(5,5))
a

array([[7, 6, 4, 2, 4],
       [6, 9, 8, 3, 3],
       [8, 9, 3, 4, 6],
       [1, 1, 4, 1, 6],
       [0, 5, 8, 1, 3]])

In [166]:
alt_a = a[0:3,0:2]
alt_a

array([[7, 6],
       [6, 9],
       [8, 9]])

In [167]:
alt_a[0,0]=9999
alt_a[1,1]=88

In [168]:
alt_a

array([[9999,    6],
       [   6,   88],
       [   8,    9]])

In [171]:
a # anaparça üzerinde de değişiklik oldu

array([[9999,    6,    4,    2,    4],
       [   6,   88,    8,    3,    3],
       [   8,    9,    3,    4,    6],
       [   1,    1,    4,    1,    6],
       [   0,    5,    8,    1,    3]])

In [172]:
m = np.random.randint(10,size=(5,5))
m

array([[1, 8, 1, 2, 0],
       [5, 0, 2, 3, 3],
       [7, 6, 6, 8, 9],
       [5, 0, 0, 2, 7],
       [6, 7, 6, 2, 3]])

In [176]:
alt_b=m[0:3,0:2].copy()#ana arrayden bağımsızlaştırır

In [177]:
alt_b[0,0]=9999

In [178]:
alt_b

array([[9999,    8],
       [   5,    0],
       [   7,    6]])

In [179]:
m

array([[1, 8, 1, 2, 0],
       [5, 0, 2, 3, 3],
       [7, 6, 6, 8, 9],
       [5, 0, 0, 2, 7],
       [6, 7, 6, 2, 3]])

## Fancy Index ile Elemanlara Erişmek

In [180]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [181]:
v[1]

3

In [182]:
v[3]

9

In [183]:
v[5]

15

In [184]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [185]:
al_getir=[1,3,5]

In [186]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [188]:
v[al_getir] #fancy index metodu

array([ 3,  9, 15])

In [189]:
#iki boyutta fancy

In [190]:
m=np.arange(9).reshape((3,3))

In [191]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [192]:
satir=np.array([0,1])

In [193]:
sutun=np.array([1,2])

In [194]:
m[satir,sutun] #fancy index metodu ile seçili olanları getirdi

array([1, 5])

In [195]:
#basit index ile fancy index

In [196]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [197]:
m[0,[1,2]]

array([1, 2])

In [198]:
#slice ile fancy

In [200]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri 

In [201]:
import numpy as np
v=np.array([1,2,3,4,5])

In [203]:
v<3

array([ True,  True, False, False, False])

In [215]:
v[v<3] # arka planda fancy çalışıyor

array([1, 2])

In [205]:
v[v>3]

array([4, 5])

In [206]:
v[v>=3]

array([3, 4, 5])

In [207]:
v[v==3]

array([3])

In [208]:
v[v!=3]

array([1, 2, 4, 5])

In [209]:
v

array([1, 2, 3, 4, 5])

In [210]:
v*2

array([ 2,  4,  6,  8, 10])

In [211]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [212]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [214]:
v**2 #kare alma işlemi

array([ 1,  4,  9, 16, 25], dtype=int32)